jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update system deps
      run: sudo apt-get update
    - name: Install system deps
      run: sudo apt-get -y install libxmlsec1-dev pkg-config
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry install
    - name: Codestyle Checks
      run: |
        python -m poetry run black . --check
        python -m poetry run isort . --check
        python -m poetry run pylint tests sqlalchemy_hero
    - name: Test with pytest
      run: |
        python -m poetry run pytest
    - name: Dependency Check
      run: |
        python -m poetry run bandit -r sqlalchemy_hero
