#name: CI Runner
#on: [push, pull_request]
#
#jobs:
#  ci:
#    strategy:
#      fail-fast: false
#      matrix:
#        python-version: ["3.8", "3.9", "3.10"]
#        poetry-version: ["1.2"]
#        os: [ubuntu-latest, macos-latest, windows-latest]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install dependencies
#        run: |
#          poetry install
#      - name: Codestyle Checks
#        run: |
#          poetry run black . --check
#          poetry run isort . --check
#          poetry run pylint tests sqlalchemy
#      - name: Test with pytest
#        run: |
#          poetry run pytest
#      - name: Dependency Check
#        run: |
#          poetry run bandit -r sqlalchemy_hero
